---
title: "Analysis"
author: ""
output: github_document
always_allow_html: true
---

# Load libraries

```{r load-packages, message = FALSE}
library(tidyverse)
library(googlesheets4)
library(openxlsx)
library(DT)
```

# Read data

```{r read-data-from-google-sheets}
#career_connections_internships <- read_sheet("https://docs.google.com/spreadsheets/d/1_iSvNe37MX_rvaBNmIgu37PffRk5jXE4qdLSiyZ-Q7w/edit#gid=0", sheet = 1,
           #gs4_deauth())

#repeat for each sheet
```


```{r read-downloaded-data}

career_connections <-"/cloud/project/data/Career_Connections_Database.xlsx"

sheets <- openxlsx::getSheetNames(career_connections)
SheetList <- lapply(sheets,openxlsx::read.xlsx,xlsxFile=career_connections)
names(SheetList) <- sheets
CombinedCareerConnections <- data.table::rbindlist(SheetList, fill = TRUE)

CombinedCareerConnections$Opportunity <- rep(sheets, sapply(SheetList, nrow))

```

# Interactive datatable

```{r interactive-datatable}

datatable(CombinedCareerConnections, options = list(
  searching = TRUE, 
  pageLength = 5,
  lengthMenu = c(5, 15, 20, 25),
  filter = 'top'
))

```

```{r format-style, eval = FALSE}
formatStyle(datatable, 
  'Application.Due', 
  backgroundColor = styleInterval(values = c('ASAP', 'Rolling basis'), colors = c('red', 'orange'))
)
```

